name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]  # Updates every Sunday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.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 }}
          user: gahabitcraft
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_followup: yes
